//! Generated protobuf types for IPC and app API.
//!
//! All code in this module is generated by `buffa-build` from the `.proto`
//! files in `proto/`. Do not edit the generated output directly.

/// Rust/Python IPC messages over Unix domain socket.
#[allow(
    unsafe_code,
    dead_code,
    non_camel_case_types,
    missing_docs,
    missing_debug_implementations,
    unreachable_pub,
    clippy::all,
    clippy::pedantic,
    clippy::nursery,
    clippy::restriction
)]
pub mod detection {
    include!(concat!(
        env!("OUT_DIR"),
        "/catlaser.detection.v1.detection.rs"
    ));
}

/// App/device API messages over WebRTC data channel or TCP.
#[allow(
    unsafe_code,
    dead_code,
    non_camel_case_types,
    missing_docs,
    missing_debug_implementations,
    unreachable_pub,
    clippy::all,
    clippy::pedantic,
    clippy::nursery,
    clippy::restriction
)]
pub mod app {
    include!(concat!(env!("OUT_DIR"), "/catlaser.app.v1.app.rs"));
}
