import { generateKeyPairSync, sign } from 'node:crypto';
import type { KeyObject } from 'node:crypto';
import type { AttestationBinding } from '~/lib/attestation-binding.ts';
import type { ParsedAttestation } from '~/lib/attestation-header.ts';
import {
  ATTESTATION_VERSION,
  FINGERPRINT_HASH_BYTES,
  encodeAttestationHeader,
} from '~/lib/attestation-header.ts';

/**
 * Shared signing helper for attestation tests. Produces real P-256
 * signatures so the v3 device-attestation plugin's verification path
 * is exercised end-to-end; earlier fake-signature fixtures only
 * reached the parse / structural checks and are no longer viable.
 *
 * Each helper is deliberately an escape-hatch-friendly interface:
 * every field on the built attestation has an `override*` companion
 * so tests can inject malformed SPKIs, swapped fingerprints, truncated
 * signatures, and so on without rebuilding the whole pipeline.
 */

export interface TestDeviceKey {
  readonly privateKey: KeyObject;
  /**
   * DER-encoded `SubjectPublicKeyInfo` for the key's public half —
   * 91 bytes for every well-formed P-256 key generated by Node's
   * `generateKeyPairSync`.
   */
  readonly publicKeySPKI: Uint8Array;
}

/**
 * Generate a fresh P-256 key pair and export its public half as a DER
 * `SubjectPublicKeyInfo`. Byte-identical prefix to what iOS's Secure
 * Enclave emits for a real device identity.
 */
export const createTestDeviceKey = (): TestDeviceKey => {
  const { privateKey, publicKey } = generateKeyPairSync('ec', { namedCurve: 'P-256' });
  const spkiDer = publicKey.export({ format: 'der', type: 'spki' });
  return { privateKey, publicKeySPKI: Uint8Array.from(spkiDer) };
};

const bindingWireValue = (binding: AttestationBinding): string => {
  switch (binding.tag) {
    case 'request':
      return `req:${binding.timestamp.toString()}`;
    case 'verify':
      return `ver:${binding.token}`;
    case 'social':
      return `sis:${binding.timestamp.toString()}:${binding.rawNonce}`;
    case 'signOut':
      return `out:${binding.timestamp.toString()}`;
    case 'api':
      return `api:${binding.timestamp.toString()}`;
    case 'deleteAccount':
      return `del:${binding.timestamp.toString()}`;
    default: {
      const exhaustive: never = binding;
      throw new Error(`unreachable: ${JSON.stringify(exhaustive)}`);
    }
  }
};

export interface BuildSignedAttestationOpts {
  readonly deviceKey: TestDeviceKey;
  readonly binding: AttestationBinding;
  /** 32-byte fingerprint digest. Defaults to a fixed pattern so round-trip
   * tests stay deterministic. */
  readonly fingerprintHash?: Uint8Array;
  /** Replace the signature bytes on the wire without touching the
   * otherwise-correct signing logic — useful for exercising the
   * plugin's `ATTESTATION_SIGNATURE_INVALID` path. */
  readonly overrideSignature?: Uint8Array;
  /** Replace the SPKI bytes on the wire. Caller owns ensuring the
   * override still survives the header parser (≥ 26 bytes); SPKI
   * structural rejections from the plugin surface as
   * `ATTESTATION_SPKI_INVALID`. */
  readonly overridePublicKeySPKI?: Uint8Array;
  /** Replace the `v` field. Non-3 values are rejected at the header
   * layer with `ATTESTATION_INVALID`. */
  readonly overrideVersion?: number;
  /** Replace the fph bytes on the wire only. The signed message still
   * uses `fingerprintHash`, so providing a different `overrideFph`
   * produces a legitimate-shape header whose signature no longer
   * matches — the plugin rejects with `ATTESTATION_SIGNATURE_INVALID`. */
  readonly overrideFph?: Uint8Array;
}

const signMessage = (privateKey: KeyObject, message: Uint8Array): Uint8Array => {
  const signature = sign('sha256', Buffer.from(message), { key: privateKey, dsaEncoding: 'der' });
  return Uint8Array.from(signature);
};

export const defaultFingerprintHash = (): Uint8Array =>
  new Uint8Array(FINGERPRINT_HASH_BYTES).fill(0xab);

/**
 * Build a fully-signed v3 attestation header for the given binding.
 * Signs over `fingerprintHash || bindingWireBytes`, matching iOS
 * `DeviceAttestationBuilder.build` byte-for-byte.
 */
export const buildSignedAttestationHeader = (opts: BuildSignedAttestationOpts): string => {
  const fingerprintHash = opts.fingerprintHash ?? defaultFingerprintHash();
  const bnd = bindingWireValue(opts.binding);
  const signedBytes = new Uint8Array(fingerprintHash.length + Buffer.byteLength(bnd, 'utf8'));
  signedBytes.set(fingerprintHash, 0);
  signedBytes.set(new TextEncoder().encode(bnd), fingerprintHash.length);
  const signature = opts.overrideSignature ?? signMessage(opts.deviceKey.privateKey, signedBytes);
  const parsed: ParsedAttestation = {
    version: opts.overrideVersion ?? ATTESTATION_VERSION,
    fingerprintHash: opts.overrideFph ?? fingerprintHash,
    publicKeySPKI: opts.overridePublicKeySPKI ?? opts.deviceKey.publicKeySPKI,
    binding: opts.binding,
    signature,
  };
  return encodeAttestationHeader(parsed);
};
